language: node_js
node_js:
  - "10" # Current Release
  - "8"  # Active LTS
  - "6"  # Maintenance LTS

os:
  - linux
  - osx

branches:
  only:
    - master
    - /^greenkeeper/.*$/

notifications:
  email: false
